<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class NationalitiesTableAdditionalSeeder extends Seeder
{
    public function run()
    {
        DB::table('nationalities')->insert([
            ['name_en' => 'Afghan', 'name_ar' => 'أفغاني', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Albanian', 'name_ar' => 'ألباني', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Algerian', 'name_ar' => 'جزائري', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Andorran', 'name_ar' => 'أندوري', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Angolan', 'name_ar' => 'أنغولي', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Antiguan and Barbudan', 'name_ar' => 'أنتيغوي وباربودي', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Argentine', 'name_ar' => 'أرجنتيني', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Armenian', 'name_ar' => 'أرمني', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Australian', 'name_ar' => 'أسترالي', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Austrian', 'name_ar' => 'نمساوي', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Azerbaijani', 'name_ar' => 'أذربيجاني', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Bahamian', 'name_ar' => 'باهامي', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Bahraini', 'name_ar' => 'بحريني', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Bangladeshi', 'name_ar' => 'بنغلاديشي', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Barbadian', 'name_ar' => 'بربادوسي', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Belarusian', 'name_ar' => 'بيلاروسي', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Belgian', 'name_ar' => 'بلجيكي', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Belizean', 'name_ar' => 'بليزي', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Beninese', 'name_ar' => 'بنيني', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Bhutanese', 'name_ar' => 'بوتاني', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Bolivian', 'name_ar' => 'بوليفي', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Bosnian and Herzegovinian', 'name_ar' => 'بوسني وهرسكي', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Botswanan', 'name_ar' => 'بوتسواني', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Brazilian', 'name_ar' => 'برازيلي', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'British', 'name_ar' => 'بريطاني', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Bruneian', 'name_ar' => 'بروناي', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Bulgarian', 'name_ar' => 'بلغاري', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Burkinabe', 'name_ar' => 'بوركيني', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Burmese', 'name_ar' => 'بورمي', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Burundian', 'name_ar' => 'بوروندي', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Cabo Verdean', 'name_ar' => 'كابوفيردي', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Cambodian', 'name_ar' => 'كمبودي', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Cameroonian', 'name_ar' => 'كاميروني', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Canadian', 'name_ar' => 'كندي', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Central African', 'name_ar' => 'وسط أفريقي', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Chadian', 'name_ar' => 'تشادي', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Chilean', 'name_ar' => 'تشيلي', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Chinese', 'name_ar' => 'صيني', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Colombian', 'name_ar' => 'كولومبي', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Comorian', 'name_ar' => 'قمري', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Congolese (Republic of the Congo)', 'name_ar' => 'كونغولي (جمهورية الكونغو)', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Congolese (DRC)', 'name_ar' => 'كونغولي (جمهورية الكونغو الديمقراطية)', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Costa Rican', 'name_ar' => 'كوستاريكي', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Croatian', 'name_ar' => 'كرواتي', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Cuban', 'name_ar' => 'كوبي', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Cypriot', 'name_ar' => 'قبرصي', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Czech', 'name_ar' => 'تشيكي', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Danish', 'name_ar' => 'دنماركي', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Djiboutian', 'name_ar' => 'جيبوتي', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Dominican (Dominica)', 'name_ar' => 'دومينيكي (دومينيكا)', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Dominican (Dominican Republic)', 'name_ar' => 'دومينيكاني (جمهورية الدومينيكان)', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Dutch', 'name_ar' => 'هولندي', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'East Timorese', 'name_ar' => 'تيموري شرقي', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Ecuadorian', 'name_ar' => 'إكوادوري', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Egyptian', 'name_ar' => 'مصري', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Salvadoran', 'name_ar' => 'سلفادوري', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Equatorial Guinean', 'name_ar' => 'غيني استوائي', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Eritrean', 'name_ar' => 'إريتري', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Estonian', 'name_ar' => 'إستوني', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Eswatini', 'name_ar' => 'إسواتيني', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Ethiopian', 'name_ar' => 'إثيوبي', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Fijian', 'name_ar' => 'فيجي', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Finnish', 'name_ar' => 'فنلندي', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'French', 'name_ar' => 'فرنسي', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Gabonese', 'name_ar' => 'غابوني', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Gambian', 'name_ar' => 'غامبي', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Georgian', 'name_ar' => 'جورجي', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'German', 'name_ar' => 'ألماني', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Ghanaian', 'name_ar' => 'غاني', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Greek', 'name_ar' => 'يوناني', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Grenadian', 'name_ar' => 'غرينادي', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Guatemalan', 'name_ar' => 'غواتيمالي', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Guinean', 'name_ar' => 'غيني', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Guinea-Bissauan', 'name_ar' => 'غيني بيساوي', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Guyanese', 'name_ar' => 'غياني', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Haitian', 'name_ar' => 'هايتي', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Honduran', 'name_ar' => 'هندوراسي', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Hungarian', 'name_ar' => 'مجري', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Icelandic', 'name_ar' => 'آيسلندي', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Indian', 'name_ar' => 'هندي', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Indonesian', 'name_ar' => 'إندونيسي', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Iranian', 'name_ar' => 'إيراني', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Iraqi', 'name_ar' => 'عراقي', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Irish', 'name_ar' => 'أيرلندي', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Israeli', 'name_ar' => 'إسرائيلي', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Italian', 'name_ar' => 'إيطالي', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Ivorian', 'name_ar' => 'إيفواري', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Jamaican', 'name_ar' => 'جامايكي', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Japanese', 'name_ar' => 'ياباني', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Jordanian', 'name_ar' => 'أردني', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Kazakhstani', 'name_ar' => 'كازاخستاني', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Kenyan', 'name_ar' => 'كيني', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Kiribati', 'name_ar' => 'كيريباتي', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'North Korean', 'name_ar' => 'كوري شمالي', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'South Korean', 'name_ar' => 'كوري جنوبي', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Kosovar', 'name_ar' => 'كوسوفي', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Kuwaiti', 'name_ar' => 'كويتي', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Kyrgyz', 'name_ar' => 'قيرغيزستاني', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Lao', 'name_ar' => 'لاوسي', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Latvian', 'name_ar' => 'لاتفي', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Lebanese', 'name_ar' => 'لبناني', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Basotho', 'name_ar' => 'ليسنغي', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Liberian', 'name_ar' => 'ليبيري', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Libyan', 'name_ar' => 'ليبي', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Liechtensteiner', 'name_ar' => 'ليختنشتايني', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Lithuanian', 'name_ar' => 'ليتواني', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Luxembourger', 'name_ar' => 'لوكسمبورغي', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Malagasy', 'name_ar' => 'مدغشقري', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Malawian', 'name_ar' => 'مالاوي', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Malaysian', 'name_ar' => 'ماليزي', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Maldivian', 'name_ar' => 'مالديفي', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Malian', 'name_ar' => 'مالي', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Maltese', 'name_ar' => 'مالطي', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Marshallese', 'name_ar' => 'مارشالي', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Mauritanian', 'name_ar' => 'موريتاني', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Mauritian', 'name_ar' => 'موريشيوسي', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Mexican', 'name_ar' => 'مكسيكي', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Micronesian', 'name_ar' => 'ميكرونيزي', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Moldovan', 'name_ar' => 'مولدوفي', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Monacan', 'name_ar' => 'موناكي', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Mongolian', 'name_ar' => 'منغولي', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Montenegrin', 'name_ar' => 'مونتينيغري', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Moroccan', 'name_ar' => 'مغربي', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Mozambican', 'name_ar' => 'موزمبيقي', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Namibian', 'name_ar' => 'ناميبي', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Nauruan', 'name_ar' => 'ناوروي', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Nepalese', 'name_ar' => 'نيبالي', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'New Zealander', 'name_ar' => 'نيوزيلندي', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Nicaraguan', 'name_ar' => 'نيكاراغوي', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Nigerien', 'name_ar' => 'نيجيري (النيجر)', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Nigerian', 'name_ar' => 'نيجيري', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Norwegian', 'name_ar' => 'نرويجي', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Omani', 'name_ar' => 'عُماني', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Pakistani', 'name_ar' => 'باكستاني', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Palauan', 'name_ar' => 'بالاوي', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Palestinian', 'name_ar' => 'فلسطيني', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Panamanian', 'name_ar' => 'بنمي', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Papua New Guinean', 'name_ar' => 'بابوي غيني جديد', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Paraguayan', 'name_ar' => 'باراغواي', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Peruvian', 'name_ar' => 'بيروفي', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Filipino', 'name_ar' => 'فلبيني', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Polish', 'name_ar' => 'بولندي', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Portuguese', 'name_ar' => 'برتغالي', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Qatari', 'name_ar' => 'قطري', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Romanian', 'name_ar' => 'روماني', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Russian', 'name_ar' => 'روسي', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Rwandan', 'name_ar' => 'رواندي', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Kittitian and Nevisian', 'name_ar' => 'كيتسي ونيفيسي', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Saint Lucian', 'name_ar' => 'سانت لوسي', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Saint Vincentian', 'name_ar' => 'سانت فينسنتي', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Samoan', 'name_ar' => 'ساموي', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Sammarinese', 'name_ar' => 'سان ماريني', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Sao Tomean', 'name_ar' => 'ساو تومي', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Saudi Arabian', 'name_ar' => 'سعودي', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Senegalese', 'name_ar' => 'سنغالي', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Serbian', 'name_ar' => 'صربي', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Seychellois', 'name_ar' => 'سيشيلي', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Sierra Leonean', 'name_ar' => 'سيرا ليوني', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Singaporean', 'name_ar' => 'سنغافوري', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Slovak', 'name_ar' => 'سلوفاكي', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Slovenian', 'name_ar' => 'سلوفيني', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Solomon Islander', 'name_ar' => 'سليماني', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Somali', 'name_ar' => 'صومالي', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'South African', 'name_ar' => 'جنوب أفريقي', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'South Sudanese', 'name_ar' => 'جنوب سوداني', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Spanish', 'name_ar' => 'إسباني', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Sri Lankan', 'name_ar' => 'سريلانكي', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Sudanese', 'name_ar' => 'سوداني', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Surinamese', 'name_ar' => 'سورينامي', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Swedish', 'name_ar' => 'سويدي', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Swiss', 'name_ar' => 'سويسري', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Syrian', 'name_ar' => 'سوري', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Taiwanese', 'name_ar' => 'تايواني', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Tajik', 'name_ar' => 'طاجيكي', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Tanzanian', 'name_ar' => 'تنزاني', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Thai', 'name_ar' => 'تايلاندي', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Togolese', 'name_ar' => 'توغولي', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Tongan', 'name_ar' => 'تونغي', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Trinidadian and Tobagonian', 'name_ar' => 'ترينيدادي وتوباغوي', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Tunisian', 'name_ar' => 'تونسي', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Turkish', 'name_ar' => 'تركي', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Turkmen', 'name_ar' => 'تركماني', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Tuvaluan', 'name_ar' => 'توفالوي', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Ugandan', 'name_ar' => 'أوغندي', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Ukrainian', 'name_ar' => 'أوكراني', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Emirati', 'name_ar' => 'إماراتي', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'American', 'name_ar' => 'أمريكي', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Uruguayan', 'name_ar' => 'أوروغواي', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Uzbek', 'name_ar' => 'أوزبكي', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Ni-Vanuatu', 'name_ar' => 'فانواتوي', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Vatican', 'name_ar' => 'فاتيكاني', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Venezuelan', 'name_ar' => 'فنزويلي', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Vietnamese', 'name_ar' => 'فيتنامي', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Yemeni', 'name_ar' => 'يمني', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Zambian', 'name_ar' => 'زامبي', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Zimbabwean', 'name_ar' => 'زيمبابوي', 'created_at' => now(), 'updated_at' => now()],
        ]);
    }
}
