<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class NonArabicCountriesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('countries')->insert([
            ['name_en' => 'Afghanistan', 'name_ar' => 'أفغانستان', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Albania', 'name_ar' => 'ألبانيا', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Andorra', 'name_ar' => 'أندورا', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Angola', 'name_ar' => 'أنغولا', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Antigua and Barbuda', 'name_ar' => 'أنتيغوا وباربودا', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Argentina', 'name_ar' => 'الأرجنتين', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Armenia', 'name_ar' => 'أرمينيا', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Australia', 'name_ar' => 'أستراليا', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Austria', 'name_ar' => 'النمسا', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Azerbaijan', 'name_ar' => 'أذربيجان', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Bahamas', 'name_ar' => 'الباهاماس', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Bangladesh', 'name_ar' => 'بنغلاديش', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Barbados', 'name_ar' => 'باربادوس', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Belarus', 'name_ar' => 'بيلاروس', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Belgium', 'name_ar' => 'بلجيكا', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Belize', 'name_ar' => 'بيليز', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Benin', 'name_ar' => 'بنين', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Bhutan', 'name_ar' => 'بوتان', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Bolivia', 'name_ar' => 'بوليفيا', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Bosnia and Herzegovina', 'name_ar' => 'البوسنة والهرسك', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Botswana', 'name_ar' => 'بوتسوانا', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Brazil', 'name_ar' => 'البرازيل', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Brunei', 'name_ar' => 'بروناي', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Bulgaria', 'name_ar' => 'بلغاريا', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Burkina Faso', 'name_ar' => 'بوركينا فاسو', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Burundi', 'name_ar' => 'بوروندي', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Cabo Verde', 'name_ar' => 'الرأس الأخضر', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Cambodia', 'name_ar' => 'كمبوديا', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Cameroon', 'name_ar' => 'الكاميرون', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Canada', 'name_ar' => 'كندا', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Central African Republic', 'name_ar' => 'جمهورية أفريقيا الوسطى', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Chad', 'name_ar' => 'تشاد', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Chile', 'name_ar' => 'تشيلي', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'China', 'name_ar' => 'الصين', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Colombia', 'name_ar' => 'كولومبيا', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Congo, Democratic Republic of the', 'name_ar' => 'جمهورية الكونغو الديمقراطية', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Congo, Republic of the', 'name_ar' => 'جمهورية الكونغو', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Costa Rica', 'name_ar' => 'كوستاريكا', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Croatia', 'name_ar' => 'كرواتيا', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Cuba', 'name_ar' => 'كوبا', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Cyprus', 'name_ar' => 'قبرص', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Czech Republic', 'name_ar' => 'جمهورية التشيك', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Denmark', 'name_ar' => 'الدنمارك', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Dominica', 'name_ar' => 'دومينيكا', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Dominican Republic', 'name_ar' => 'جمهورية الدومينيكان', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Ecuador', 'name_ar' => 'الإكوادور', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'El Salvador', 'name_ar' => 'السلفادور', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Equatorial Guinea', 'name_ar' => 'غينيا الاستوائية', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Eritrea', 'name_ar' => 'إريتريا', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Estonia', 'name_ar' => 'إستونيا', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Eswatini', 'name_ar' => 'إسواتيني', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Ethiopia', 'name_ar' => 'إثيوبيا', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Fiji', 'name_ar' => 'فيجي', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Finland', 'name_ar' => 'فنلندا', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'France', 'name_ar' => 'فرنسا', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Gabon', 'name_ar' => 'الغابون', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Gambia', 'name_ar' => 'غامبيا', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Georgia', 'name_ar' => 'جورجيا', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Germany', 'name_ar' => 'ألمانيا', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Ghana', 'name_ar' => 'غانا', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Greece', 'name_ar' => 'اليونان', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Grenada', 'name_ar' => 'غرينادا', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Guatemala', 'name_ar' => 'غواتيمالا', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Guinea', 'name_ar' => 'غينيا', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Guinea-Bissau', 'name_ar' => 'غينيا بيساو', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Guyana', 'name_ar' => 'غيانا', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Haiti', 'name_ar' => 'هايتي', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Honduras', 'name_ar' => 'هندوراس', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Hungary', 'name_ar' => 'هنغاريا', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Iceland', 'name_ar' => 'آيسلندا', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'India', 'name_ar' => 'الهند', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Indonesia', 'name_ar' => 'إندونيسيا', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Iran', 'name_ar' => 'إيران', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Ireland', 'name_ar' => 'أيرلندا', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Italy', 'name_ar' => 'إيطاليا', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Jamaica', 'name_ar' => 'جامايكا', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Japan', 'name_ar' => 'اليابان', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Kazakhstan', 'name_ar' => 'كازاخستان', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Kenya', 'name_ar' => 'كينيا', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Kiribati', 'name_ar' => 'كيريباتي', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Korea, North', 'name_ar' => 'كوريا الشمالية', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Korea, South', 'name_ar' => 'كوريا الجنوبية', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Kyrgyzstan', 'name_ar' => 'قيرغيزستان', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Laos', 'name_ar' => 'لاوس', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Latvia', 'name_ar' => 'لاتفيا', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Lesotho', 'name_ar' => 'ليسوتو', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Liberia', 'name_ar' => 'ليبيريا', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Liechtenstein', 'name_ar' => 'ليختنشتاين', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Lithuania', 'name_ar' => 'ليتوانيا', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Luxembourg', 'name_ar' => 'لوكسمبورغ', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Madagascar', 'name_ar' => 'مدغشقر', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Malawi', 'name_ar' => 'مالاوي', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Malaysia', 'name_ar' => 'ماليزيا', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Maldives', 'name_ar' => 'المالديف', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Mali', 'name_ar' => 'مالي', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Malta', 'name_ar' => 'مالطا', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Marshall Islands', 'name_ar' => 'جزر مارشال', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Mauritius', 'name_ar' => 'موريشيوس', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Mexico', 'name_ar' => 'المكسيك', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Micronesia', 'name_ar' => 'ميكرونيزيا', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Moldova', 'name_ar' => 'مولدوفا', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Monaco', 'name_ar' => 'موناكو', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Mongolia', 'name_ar' => 'منغوليا', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Montenegro', 'name_ar' => 'الجبل الأسود', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Mozambique', 'name_ar' => 'موزمبيق', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Myanmar', 'name_ar' => 'ميانمار', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Namibia', 'name_ar' => 'ناميبيا', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Nauru', 'name_ar' => 'ناورو', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Nepal', 'name_ar' => 'نيبال', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Netherlands', 'name_ar' => 'هولندا', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'New Zealand', 'name_ar' => 'نيوزيلندا', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Nicaragua', 'name_ar' => 'نيكاراغوا', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Niger', 'name_ar' => 'النيجر', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Nigeria', 'name_ar' => 'نيجيريا', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'North Macedonia', 'name_ar' => 'مقدونيا الشمالية', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Norway', 'name_ar' => 'النرويج', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Pakistan', 'name_ar' => 'باكستان', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Palau', 'name_ar' => 'بالاو', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Panama', 'name_ar' => 'بنما', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Papua New Guinea', 'name_ar' => 'بابوا غينيا الجديدة', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Paraguay', 'name_ar' => 'باراغواي', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Peru', 'name_ar' => 'بيرو', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Philippines', 'name_ar' => 'الفلبين', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Poland', 'name_ar' => 'بولندا', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Portugal', 'name_ar' => 'البرتغال', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Romania', 'name_ar' => 'رومانيا', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Russia', 'name_ar' => 'روسيا', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Rwanda', 'name_ar' => 'رواندا', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Saint Kitts and Nevis', 'name_ar' => 'سانت كيتس ونيفيس', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Saint Lucia', 'name_ar' => 'سانت لوسيا', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Saint Vincent and the Grenadines', 'name_ar' => 'سانت فينسنت والغرينادين', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Samoa', 'name_ar' => 'ساموا', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'San Marino', 'name_ar' => 'سان مارينو', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Sao Tome and Principe', 'name_ar' => 'ساو تومي وبرينسيب', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Senegal', 'name_ar' => 'السنغال', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Serbia', 'name_ar' => 'صربيا', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Seychelles', 'name_ar' => 'سيشيل', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Sierra Leone', 'name_ar' => 'سيراليون', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Singapore', 'name_ar' => 'سنغافورة', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Slovakia', 'name_ar' => 'سلوفاكيا', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Slovenia', 'name_ar' => 'سلوفينيا', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Solomon Islands', 'name_ar' => 'جزر سليمان', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'South Africa', 'name_ar' => 'جنوب أفريقيا', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'South Sudan', 'name_ar' => 'جنوب السودان', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Spain', 'name_ar' => 'إسبانيا', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Sri Lanka', 'name_ar' => 'سريلانكا', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Suriname', 'name_ar' => 'سورينام', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Sweden', 'name_ar' => 'السويد', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Switzerland', 'name_ar' => 'سويسرا', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Taiwan', 'name_ar' => 'تايوان', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Tajikistan', 'name_ar' => 'طاجيكستان', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Tanzania', 'name_ar' => 'تنزانيا', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Thailand', 'name_ar' => 'تايلاند', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Timor-Leste', 'name_ar' => 'تيمور الشرقية', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Togo', 'name_ar' => 'توغو', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Tonga', 'name_ar' => 'تونغا', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Trinidad and Tobago', 'name_ar' => 'ترينيداد وتوباغو', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Turkey', 'name_ar' => 'تركيا', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Turkmenistan', 'name_ar' => 'تركمانستان', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Tuvalu', 'name_ar' => 'توفالو', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Uganda', 'name_ar' => 'أوغندا', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Ukraine', 'name_ar' => 'أوكرانيا', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'United Kingdom', 'name_ar' => 'المملكة المتحدة', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'United States', 'name_ar' => 'الولايات المتحدة', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Uruguay', 'name_ar' => 'أوروغواي', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Uzbekistan', 'name_ar' => 'أوزبكستان', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Vanuatu', 'name_ar' => 'فانواتو', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Vatican City', 'name_ar' => 'الفاتيكان', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Venezuela', 'name_ar' => 'فنزويلا', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Vietnam', 'name_ar' => 'فيتنام', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Zambia', 'name_ar' => 'زامبيا', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Zimbabwe', 'name_ar' => 'زيمبابوي', 'created_at' => now(), 'updated_at' => now()],
        ]);
    }
}
