<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class SpecializationsTableSeeder extends Seeder
{
    public function run()
    {
        DB::table('specializations')->insert([
            ['name_en' => 'Chiropractor', 'name_ar' => 'مقوم العظام', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Dentist', 'name_ar' => 'طبيب أسنان', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Dietitian or Nutritionist', 'name_ar' => 'أخصائي تغذية', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Optometrist', 'name_ar' => 'أخصائي بصريات', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Pharmacist', 'name_ar' => 'صيدلي', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Physician', 'name_ar' => 'طبيب', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Physician Assistant', 'name_ar' => 'مساعد طبيب', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Podiatrist', 'name_ar' => 'طبيب أقدام', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Registered Nurse', 'name_ar' => 'ممرض مسجل', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Therapist', 'name_ar' => 'معالج', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Veterinarian', 'name_ar' => 'طبيب بيطري', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Health Technologist or Technician', 'name_ar' => 'فني أو تقني صحي', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Other Healthcare Practitioners and Technical Occupation', 'name_ar' => 'مهنة صحية أو فنية أخرى', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Nursing, Psychiatric, or Home Health Aide', 'name_ar' => 'مساعد تمريض أو نفسي أو منزلي', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Occupational and Physical Therapist Assistant or Aide', 'name_ar' => 'مساعد أو معاون معالج وظيفي أو طبيعي', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Other Healthcare Support Occupation', 'name_ar' => 'مهنة دعم صحي أخرى', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Chief Executive', 'name_ar' => 'المدير التنفيذي', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'General and Operations Manager', 'name_ar' => 'مدير عام أو مدير عمليات', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Advertising, Marketing, Promotions, Public Relations, and Sales Manager', 'name_ar' => 'مدير دعاية وتسويق ومبيعات وعلاقات عامة', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Operations Specialties Manager (e.g., IT or HR Manager)', 'name_ar' => 'مدير تخصص عمليات (مثل مدير تقنية أو موارد بشرية)', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Construction Manager', 'name_ar' => 'مدير إنشاءات', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Engineering Manager', 'name_ar' => 'مدير هندسي', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Accountant, Auditor', 'name_ar' => 'محاسب أو مدقق', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Business Operations or Financial Specialist', 'name_ar' => 'اختصاصي عمليات تجارية أو مالية', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Business Owner', 'name_ar' => 'صاحب عمل', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Other Business, Executive, Management, Financial Occupation', 'name_ar' => 'مهنة تجارية أو إدارية أو مالية أخرى', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Architect, Surveyor, or Cartographer', 'name_ar' => 'مهندس معماري أو مساح أو رسام خرائط', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Engineer', 'name_ar' => 'مهندس', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Other Architecture and Engineering Occupation', 'name_ar' => 'مهنة هندسة أو عمارة أخرى', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Postsecondary Teacher (e.g., College Professor)', 'name_ar' => 'مدرس جامعي', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Primary, Secondary, or Special Education School Teacher', 'name_ar' => 'معلم تعليم أساسي أو ثانوي أو خاص', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Other Teacher or Instructor', 'name_ar' => 'مدرس أو معلم آخر', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Other Education, Training, and Library Occupation', 'name_ar' => 'مهنة تعليم أو تدريب أو مكتبة أخرى', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Computer Specialist, Mathematical Science', 'name_ar' => 'مختص حاسوب أو علوم رياضية', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Lawyer, Judge', 'name_ar' => 'محامٍ أو قاضٍ', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Counselor, Social Worker, or Other Community and Social Service Specialist', 'name_ar' => 'مستشار أو عامل اجتماعي أو اختصاصي خدمة اجتماعية', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Life Scientist (e.g., Animal, Food, Soil, or Biological Scientist, Zoologist)', 'name_ar' => 'عالم علوم حياتية', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Physical Scientist (e.g., Astronomer, Physicist, Chemist, Hydrologist)', 'name_ar' => 'عالم فيزيائي (مثل فيزيائي أو كيميائي)', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Religious Worker (e.g., Clergy, Director of Religious Activities or Education)', 'name_ar' => 'عامل ديني (مثل رجل دين)', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Social Scientist and Related Worker', 'name_ar' => 'عالم اجتماع أو ما شابه', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Other Professional Occupation', 'name_ar' => 'مهنة احترافية أخرى', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Supervisor of Administrative Support Workers', 'name_ar' => 'مشرف عمال الدعم الإداري', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Financial Clerk', 'name_ar' => 'كاتب مالي', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Secretary or Administrative Assistant', 'name_ar' => 'سكرتير أو مساعد إداري', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Material Recording, Scheduling, and Dispatching Worker', 'name_ar' => 'عامل تسجيل المواد، الجدولة، والتوزيع', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Other Office and Administrative Support Occupation', 'name_ar' => 'مهنة دعم إداري أخرى', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Protective Service (e.g., Fire Fighting, Police Officer, Correctional Officer)', 'name_ar' => 'خدمة الحماية (مثل الإطفاء أو الشرطة)', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Chef or Head Cook', 'name_ar' => 'طاهٍ رئيسي أو شيف', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Cook or Food Preparation Worker', 'name_ar' => 'عامل تحضير طعام أو طاهٍ', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Food and Beverage Serving Worker (e.g., Bartender, Waiter, Waitress)', 'name_ar' => 'عامل تقديم الطعام والشراب (مثل نادل أو ساقي)', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Building and Grounds Cleaning and Maintenance', 'name_ar' => 'تنظيف وصيانة المباني والأراضي', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Personal Care and Service (e.g., Hairdresser, Flight Attendant, Concierge)', 'name_ar' => 'خدمة ورعاية شخصية (مثل الحلاق أو المضيف الجوي)', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Sales Supervisor, Retail Sales', 'name_ar' => 'مشرف مبيعات التجزئة', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Retail Sales Worker', 'name_ar' => 'عامل مبيعات التجزئة', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Insurance Sales Agent', 'name_ar' => 'وكيل مبيعات تأمين', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Sales Representative', 'name_ar' => 'مندوب مبيعات', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Real Estate Sales Agent', 'name_ar' => 'وكيل عقارات', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Other Services Occupation', 'name_ar' => 'مهنة خدمات أخرى', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Construction and Extraction (e.g., Construction Laborer, Electrician)', 'name_ar' => 'الإنشاءات والاستخراج (مثل العامل أو الكهربائي)', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Farming, Fishing, and Forestry', 'name_ar' => 'الزراعة، الصيد، والغابات', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Installation, Maintenance, and Repair', 'name_ar' => 'التركيب، الصيانة، والإصلاح', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Production Occupations', 'name_ar' => 'مهن الإنتاج', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Other Agriculture, Maintenance, Repair, and Skilled Crafts Occupation', 'name_ar' => 'مهنة زراعية أو صيانة أو إصلاح أو حرفة ماهرة أخرى', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Aircraft Pilot or Flight Engineer', 'name_ar' => 'طيار أو مهندس طيران', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Motor Vehicle Operator (e.g., Ambulance, Bus, Taxi, or Truck Driver)', 'name_ar' => 'سائق مركبة (مثل سيارة إسعاف أو شاحنة)', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Other Transportation Occupation', 'name_ar' => 'مهنة نقل أخرى', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Military', 'name_ar' => 'عسكري', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Homemaker', 'name_ar' => 'ربة/رب منزل', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Other Occupation', 'name_ar' => 'مهنة أخرى', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Don\'t Know', 'name_ar' => 'لا أعرف', 'created_at' => now(), 'updated_at' => now()],
            ['name_en' => 'Not Applicable', 'name_ar' => 'غير قابل للتطبيق', 'created_at' => now(), 'updated_at' => now()],
        ]);
    }
}
